swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /notitie:
    get:
      summary: Returns a list of notitie.
      description: Optional extended description in Markdown.
      operationId: getNote
      produces:
        - application/json
      responses:
        200:
          description: OK
    post:
      summary: creates a new notitie
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: OK
      parameters:
        - in: body
          name: notitie
          description: notitie to create
          schema:
            type: object
            required:
              - tekst
            properties:
              notitieId:
                type: integer
              tekst:
                type: string
              aangemaakt:
                type: string
              laatsteBerwerkt:
                type: string